#!/usr/bin/env python3
"""
LLM Code Analysis Script

Retrieves the code diff for a pull request or push event, sends it to the
OpenAI API for a detailed code review, posts the feedback as a PR comment
(for pull_request events), and always saves the feedback to a file that is
uploaded as a GitHub Actions artifact.
"""

import json
import os
import subprocess
import sys
from datetime import datetime, timezone

import requests
from openai import OpenAI

# Maximum number of characters of diff content sent to OpenAI.
# Diffs larger than this are truncated to stay within model token limits.
MAX_DIFF_LENGTH = 15_000

# OpenAI model used for the code review.
OPENAI_MODEL = os.environ.get("OPENAI_MODEL", "gpt-4o")


# ---------------------------------------------------------------------------
# Diff helpers
# ---------------------------------------------------------------------------

def _run_git_diff(*args: str) -> str:
    """Run `git diff <args>` and return stdout."""
    result = subprocess.run(
        ["git", "diff"] + list(args),
        capture_output=True,
        text=True,
    )
    return result.stdout


def get_diff() -> str:
    """Return the relevant diff depending on the GitHub event type."""
    event_name = os.environ.get("GITHUB_EVENT_NAME", "push")

    if event_name == "pull_request":
        base_sha = os.environ.get("GITHUB_BASE_SHA", "")
        head_sha = os.environ.get("GITHUB_SHA", "HEAD")
        if base_sha:
            return _run_git_diff(base_sha, head_sha)
        # Fallback when base SHA is not available
        return _run_git_diff("HEAD~1", "HEAD")

    # push event
    before_sha = os.environ.get("GITHUB_BEFORE_SHA", "")
    head_sha = os.environ.get("GITHUB_SHA", "HEAD")

    # On an initial push 'before' is all zeros — fall back to the last commit.
    if not before_sha or before_sha == "0" * 40:
        return _run_git_diff("HEAD~1", "HEAD")

    return _run_git_diff(before_sha, head_sha)


# ---------------------------------------------------------------------------
# OpenAI analysis
# ---------------------------------------------------------------------------

SYSTEM_PROMPT = """You are an expert software engineer performing a code review. \
Analyse the provided git diff and give clear, constructive feedback covering:

1. **Code quality & best practices** – naming, structure, design patterns.
2. **Bugs & correctness** – logic errors, edge cases, incorrect assumptions.
3. **Security** – injection risks, secrets, unsafe operations, dependency issues.
4. **Performance** – unnecessary allocations, algorithmic complexity, I/O.
5. **Readability & maintainability** – clarity, documentation, test coverage.
6. **Actionable suggestions** – concrete improvements with brief rationale.

Be specific: reference file names and line numbers where possible. \
If the diff is clean and well-written, say so explicitly."""


def analyze_with_openai(diff: str) -> str:
    """Send *diff* to OpenAI and return the review text."""
    client = OpenAI(api_key=os.environ["OPENAI_API_KEY"])

    user_message = (
        "Please review the following code changes:\n\n"
        "```diff\n"
        f"{diff}\n"
        "```\n\n"
        "Provide a comprehensive code review with specific feedback and suggestions."
    )

    response = client.chat.completions.create(
        model=OPENAI_MODEL,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_message},
        ],
        temperature=0.3,
        max_tokens=2048,
    )

    return response.choices[0].message.content


# ---------------------------------------------------------------------------
# GitHub API helpers
# ---------------------------------------------------------------------------

def post_pr_comment(feedback: str, pr_number: int) -> None:
    """Post *feedback* as a comment on the pull request."""
    token = os.environ.get("GITHUB_TOKEN")
    repo = os.environ.get("GITHUB_REPOSITORY")

    if not token or not repo:
        print("GITHUB_TOKEN or GITHUB_REPOSITORY not set – skipping PR comment.")
        return

    body = (
        "## 🤖 LLM Code Review\n\n"
        f"{feedback}\n\n"
        "---\n"
        f"*Generated by [{OPENAI_MODEL}](https://platform.openai.com/docs/models) "
        "via the [llm-code-analysis](https://github.com/Goldbursch/llm-code-analysis) workflow.*"
    )

    url = f"https://api.github.com/repos/{repo}/issues/{pr_number}/comments"
    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json",
    }
    resp = requests.post(url, headers=headers, json={"body": body}, timeout=30)

    if resp.status_code == 201:
        print(f"✅  Comment posted to PR #{pr_number}.")
    else:
        print(
            f"⚠️  Failed to post PR comment "
            f"(HTTP {resp.status_code}): {resp.text[:200]}"
        )


# ---------------------------------------------------------------------------
# Persistence
# ---------------------------------------------------------------------------

def save_feedback(feedback: str, event_name: str, sha: str) -> str:
    """Save *feedback* to the ``feedback/`` directory and return the file path."""
    os.makedirs("feedback", exist_ok=True)
    now = datetime.now(timezone.utc)
    timestamp = now.strftime("%Y%m%dT%H%M%SZ")
    filename = f"feedback/{event_name}_{sha[:8]}_{timestamp}.md"

    with open(filename, "w", encoding="utf-8") as fh:
        fh.write("# LLM Code Review Feedback\n\n")
        fh.write(f"| Field | Value |\n|---|---|\n")
        fh.write(f"| **Event** | `{event_name}` |\n")
        fh.write(f"| **Commit** | `{sha}` |\n")
        fh.write(f"| **Model** | `{OPENAI_MODEL}` |\n")
        fh.write(f"| **Timestamp** | {now.isoformat()} |\n\n")
        fh.write("---\n\n")
        fh.write(feedback)
        fh.write("\n")

    print(f"💾  Feedback saved to `{filename}`.")
    return filename


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    event_name = os.environ.get("GITHUB_EVENT_NAME", "push")
    github_sha = os.environ.get("GITHUB_SHA", "unknown")
    event_path = os.environ.get("GITHUB_EVENT_PATH", "")

    # Parse the GitHub event payload.
    event_data: dict = {}
    if event_path and os.path.exists(event_path):
        with open(event_path, encoding="utf-8") as fh:
            event_data = json.load(fh)

    # ------------------------------------------------------------------
    # Obtain the diff
    # ------------------------------------------------------------------
    print(f"ℹ️  Event: {event_name}  |  SHA: {github_sha[:8]}")
    print("🔍  Fetching diff …")
    diff = get_diff()

    if not diff.strip():
        print("ℹ️  No diff detected – nothing to review.")
        sys.exit(0)

    if len(diff) > MAX_DIFF_LENGTH:
        print(
            f"⚠️  Diff is {len(diff):,} characters; "
            f"truncating to ~{MAX_DIFF_LENGTH:,} characters."
        )
        # Truncate at the last newline within the limit so the diff remains
        # structurally intact (no partial lines sent to the model).
        cutoff = diff.rfind("\n", 0, MAX_DIFF_LENGTH)
        if cutoff == -1:
            cutoff = MAX_DIFF_LENGTH
        diff = diff[:cutoff] + "\n\n[… diff truncated due to size …]"

    # ------------------------------------------------------------------
    # Call OpenAI
    # ------------------------------------------------------------------
    print(f"🤖  Sending diff to OpenAI ({OPENAI_MODEL}) …")
    feedback = analyze_with_openai(diff)

    # ------------------------------------------------------------------
    # Save feedback
    # ------------------------------------------------------------------
    save_feedback(feedback, event_name, github_sha)

    # ------------------------------------------------------------------
    # Post PR comment
    # ------------------------------------------------------------------
    if event_name == "pull_request":
        pr_number = event_data.get("pull_request", {}).get("number")
        if pr_number:
            post_pr_comment(feedback, pr_number)

    # ------------------------------------------------------------------
    # Print to workflow log for visibility
    # ------------------------------------------------------------------
    print("\n" + "=" * 60)
    print("LLM Code Review")
    print("=" * 60)
    print(feedback)
    print("=" * 60)
    print("\n✅  Analysis complete.")


if __name__ == "__main__":
    main()
